---
engines:
  csslint:
    enabled: true
  duplication:
    enabled: true
    exclude_fingerprints:
    - 524ea6c817020ff2d9743c362efd63b9
    config:
      languages:
      - javascript
      - php
  eslint:
    enabled: true
  fixme:
    enabled: true
  phpmd:
    enabled: true
ratings:
  paths:
  - "**.css"
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- "frontend/config"
- "frontend/public"
- "frontend/scripts"
- "app/"
- "bin/"
- "**.spec.js"
- "var/"
- "vendor/"
- "web/"
