language: php
git:
    depth: 1
matrix:
    include:
        - php: 5.6
        - php: 7.0

before_install:
    - stty cols 120
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI_FILE
    - mysql -e 'create database symfony'

install:
    - composer install --dev --no-interaction
    # coveralls preparation
    - composer require satooshi/php-coveralls
    - mkdir -p build/logs
    - bin/console doctrine:database:create --if-not-exists
    - bin/console doctrine:schema:create

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v