language: php
git:
    depth: 1
matrix:
    include:
        - php: 5.6
        - php: 7.0

before_script:
    - stty cols 120
    - composer install --no-interaction

script:
    - ./vendor/bin/phpunit