language: php, node_js
node_js: 6
git:
    depth: 1
matrix:
    include:
        - php: 5.6
        - php: 7.0

before_install:
    - stty cols 120
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI_FILE
    - mysql -e 'create database symfony'
    - mkdir -p ./var/jwt
    - openssl genrsa -out var/jwt/private.pem 2048
    - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem
install:
    - composer install --dev --no-interaction
    - mkdir -p build/logs
    - npm install
    - npm build

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - npm test

#after_success:
#    - travis_retry php vendor/bin/coveralls -v