language: php
sudo: required
env:
    - NODE_RELEASE=6.x
php:
  - 5.6
  - 7
git:
    depth: 1

before_install:
    - stty cols 120
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI_FILE
    - mysql -e 'create database symfony'
    - mkdir -p ./var/jwt
    - openssl genrsa -out var/jwt/private.pem 2048
    - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem
    # node installation
    - sudo rm -rf ~/.nvm
    - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
    - sudo apt-get install -y nodejs

install:
    - composer install --dev --no-interaction
    - mkdir -p build/logs
    - npm install
    - cd frontend && npm install
    - bin/console doctrine:database:create -n --env=test

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
    - npm run test

#after_success:
#    - travis_retry php vendor/bin/coveralls -v