language: php
sudo: required
env:
    - NODE_RELEASE=6.x
php:
  - 5.6
  - 7
git:
    depth: 1
cache:
  directories:
  - node_modules
  - vendor
  - frontend/node_modules
before_install:
    - stty cols 120
    - INI_FILE=~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - echo memory_limit = -1 >> $INI_FILE
    - mysql -e 'create database symfony'
    - mkdir -p ./var/jwt
    - openssl genrsa -out var/jwt/private.pem 2048
    - openssl rsa -pubout -in var/jwt/private.pem -out var/jwt/public.pem
    # node installation
    - sudo rm -rf ~/.nvm
    - curl -sL "https://deb.nodesource.com/setup_${NODE_RELEASE}" | sudo -E bash -
    - sudo apt-get install -y nodejs
    - npm install -g codeclimate-test-reporter

install:
    - composer install --dev --no-interaction
    - composer require --dev codeclimate/php-test-reporter dev-master
    - mkdir -p build/logs
    - bin/console doctrine:database:create -n --env=test
    - bin/console doctrine:schema:update --force -n --env=test
    - cd frontend

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml --coverage-text
    - cd frontend
    - npm test -- --coverage
    - cd $TRAVIS_BUILD_DIR

after_success:
    - ./vendor/bin/test-reporter
    - codeclimate-test-reporter < frontend/coverage/lcov.info