language: php
services:
    - mysql
git:
    depth: 1
matrix:
    include:
        - php: 5.6
        - php: 7.0

before_script:
    - stty cols 120
    - mysql -e 'create database symfony'
    - composer install --dev --no-interaction
    # coveralls preparation
    - composer require satooshi/php-coveralls
    - mkdir -p build/logs

script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_success:
    - travis_retry php vendor/bin/coveralls -v