imports:
    - { resource: "@UserBundle/Resources/config/config.yml" }

framework:
    csrf_protection: false #only use for public API
    translator:      { fallbacks: ["%locale%"] }

fos_rest:
    routing_loader:
        default_format: json
    param_fetcher_listener: true
    body_listener: true
    #disable_csrf_role: ROLE_USER
    body_converter:
        enabled: true
    view:
        view_response_listener: force
        formats:
            json: true
            xml: true
            html: true
    format_listener:
        enabled: true
        rules:
            - { path: '^/api', priorities: ['json'], fallback_format: 'json' }
            - { path: '^/', priorities: ['html'] }


nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: []
        allow_headers: []
        allow_methods: []
        expose_headers: []
        max_age: 0
    paths:
        '^/api/':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

sensio_framework_extra:
    request: { converters: true }
    view:    { annotations: true }
    router:  { annotations: true }

jms_serializer:
    metadata:
        auto_detection: true
        directories:
            FOSUserBundle:
                namespace_prefix: "FOS\\UserBundle"
                path: "@UserBundle/Resources/config/serializer"
            DemoUserBundle:
                namespace_prefix: "Demo\\UserBundle"
                path: "@UserBundle/Resources/config/serializer"

bazinga_hateoas: ~

nelmio_api_doc:
    name: "Anthonius Munthi Demo API Documentation"

lexik_jwt_authentication:
    private_key_path: "%kernel.root_dir%/../var/jwt/private.pem"
    public_key_path:  "%kernel.root_dir%/../var/jwt/public.pem"
    pass_phrase:      "%secret%"
    token_ttl:        3600
