Demo\UserBundle\Entity\User:
    exclusion_policy: ALL
    properties:
        fullname:
            expose: true

    relations:
        -
            rel: self
            href:
                route: api_user_get
                parameters:
                    username: expr(object.getUsername())
                absolute: true